//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ec2Manager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ami-3d160149")]
        public string DefaultAMI {
            get {
                return ((string)(this["DefaultAMI"]));
            }
            set {
                this["DefaultAMI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ubuntu")]
        public string DefaultLogonUser {
            get {
                return ((string)(this["DefaultLogonUser"]));
            }
            set {
                this["DefaultLogonUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://canton7-ec2manager.s3.amazonaws.com/snapshot-config.txt")]
        public string SnapshotConfigUrl {
            get {
                return ((string)(this["SnapshotConfigUrl"]));
            }
            set {
                this["SnapshotConfigUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://portal.aws.amazon.com/gp/aws/securityCredentials")]
        public string AwsCredentialsUrl {
            get {
                return ((string)(this["AwsCredentialsUrl"]));
            }
            set {
                this["AwsCredentialsUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Testy")]
        public string HomePageUrl {
            get {
                return ((string)(this["HomePageUrl"]));
            }
            set {
                this["HomePageUrl"] = value;
            }
        }
    }
}
