//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ec2Manager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ami-3d160149")]
        public string AMI {
            get {
                return ((string)(this["AMI"]));
            }
            set {
                this["AMI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ubuntu")]
        public string LogonUser {
            get {
                return ((string)(this["LogonUser"]));
            }
            set {
                this["LogonUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://canton7-ec2manager.s3.amazonaws.com/snapshot-config.txt")]
        public string SnapshotConfigUrl {
            get {
                return ((string)(this["SnapshotConfigUrl"]));
            }
            set {
                this["SnapshotConfigUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://portal.aws.amazon.com/gp/aws/securityCredentials?#access_credentials")]
        public string AwsCredentialsUrl {
            get {
                return ((string)(this["AwsCredentialsUrl"]));
            }
            set {
                this["AwsCredentialsUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/canton7/ec2manager")]
        public string HomePageUrl {
            get {
                return ((string)(this["HomePageUrl"]));
            }
            set {
                this["HomePageUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://console.aws.amazon.com/ec2/home?region=eu-west-1")]
        public string Ec2ConsoleUrl {
            get {
                return ((string)(this["Ec2ConsoleUrl"]));
            }
            set {
                this["Ec2ConsoleUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://aws.amazon.com/ec2/pricing/#on-demand")]
        public string Ec2PricingUrl {
            get {
                return ((string)(this["Ec2PricingUrl"]));
            }
            set {
                this["Ec2PricingUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://canton7-ec2manager.s3.amazonaws.com/current-version.txt")]
        public string CurrentVersionUrl {
            get {
                return ((string)(this["CurrentVersionUrl"]));
            }
            set {
                this["CurrentVersionUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://canton7-ec2manager.s3.amazonaws.com/Releases/Ec2Manager-latest.exe")]
        public string InstallerDownloadUrl {
            get {
                return ((string)(this["InstallerDownloadUrl"]));
            }
            set {
                this["InstallerDownloadUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35864617156")]
        public string DefaultImagesUserId {
            get {
                return ((string)(this["DefaultImagesUserId"]));
            }
            set {
                this["DefaultImagesUserId"] = value;
            }
        }
    }
}
